# Generated by Django 4.1.7 on 2023-03-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtitle', models.CharField(max_length=30)),
                ('iimg', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
                ('desc', models.CharField(default='NA', max_length=100)),
            ],
        ),
    ]
