# Generated by Django 4.1.7 on 2023-04-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feane', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField(max_length=100)),
                ('quantity', models.IntegerField(max_length=5)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
